project_id = "jfiepcajyctszbfskgfu"

[functions.admin-update-email]
verify_jwt = false

[functions.custom-email]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.telegram-bot-webhook]
verify_jwt = false

[functions.broadcast-sms]
verify_jwt = false

[functions.preview-voucher]
verify_jwt = false

[functions.verify-qr-code]
verify_jwt = false

[functions.verify-merchant-pin]
verify_jwt = false

[functions.delete-voucher]
verify_jwt = false

[functions.cleanup-expired-vouchers]
verify_jwt = false

[functions.process-donation]
verify_jwt = false

[functions.get-reference-data]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-blood-request-sms]
verify_jwt = false

[functions.send-telegram-notification]
verify_jwt = false

[functions.verify-hospital-pin]
verify_jwt = false

[functions.update-blood-stock]
verify_jwt = false

[functions.create-hospital]
verify_jwt = false

[functions.manage-blood-unit]
verify_jwt = false
