project_id = "jfiepcajyctszbfskgfu"

[functions.admin-update-email]
verify_jwt = false

[functions.custom-email]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.telegram-bot-webhook]
verify_jwt = false

[functions.broadcast-sms]
verify_jwt = false

[functions.preview-voucher]
verify_jwt = false

[functions.verify-qr-code]
verify_jwt = false

[functions.verify-merchant-pin]
verify_jwt = false
